config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'properties#index'

  resources :properties do
    get :own_properties, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/community.rb
class Community < ApplicationRecord
  validates :name, presence: true
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = where(nil)
      filtering_params.each do |key, value|
        results = results.public_send("filter_by_#{key}", value) if value.present?
      end
      results
    end
  end
end

app/models/property.rb
class Property < ApplicationRecord
  include Filterable

  RENT_TYPE = 'rent'
  SALE_TYPE = 'sale'

  belongs_to :community
  belongs_to :user

  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end

  validates :operation_type, inclusion: [RENT_TYPE, SALE_TYPE], allow_blank: false
  validates :price, numericality: { greater_than: 0 }
  validates :area, numericality: { greater_than: 0, allow_blank: true }
  validates :number_of_rooms, numericality: { greater_than: 0, only_integer: true }
  validates :number_of_bathrooms, numericality: { greater_than: 0, only_integer: true }

  validates :description, no_url: true
  validates :description, no_contain: true
  validates :description, no_contain: { format: /\b\d{3}\)?[\s|-]?\d{3}-?\d{4}\b/i,
                                        message: I18n.t('cannot_contain_phone_numer') }

  scope :filter_by_operation_type, ->(operation_type) { where operation_type: }
  scope :filter_by_community, ->(community_id) { where community_id: }
  scope :filter_by_number_of_rooms, ->(number_of_rooms) { where number_of_rooms: }

  delegate :name, to: :community, prefix: true, allow_nil: false

  def rent?
    operation_type == RENT_TYPE
  end

  def sale?
    operation_type == SALE_TYPE
  end

  def price_in_usd?
    currency == 'USD'
  end

  def price_in_clp?
    currency == 'CLP'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :properties, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_own_property, only: %i[edit update destroy]

  def index
    @properties = Property.filter(filtering_params).includes(:community).page(params[:page])
  end

  def show
    @property = Property.find(params[:id])
  end

  def new
    @property = Property.new
  end

  def edit; end

  def create
    @property = current_user.properties.build(property_params)

    if @property.save
      flash[:success] = t('record_create_success')
      redirect_to own_properties_properties_path
    else
      render :new
    end
  end

  def update
    if @property.update(property_params)
      flash[:success] = t('record_update_success')
      redirect_to own_properties_properties_path
    else
      render :edit
    end
  end

  def destroy
    if @property.destroy
      flash[:success] = t('record_destroy_success')
    else
      flash[:danger] = t('record_destroy_fail')
    end

    redirect_to own_properties_properties_path
  end

  def own_properties
    @properties = current_user.properties.includes(:community).page(params[:page])
  end

  private

  def property_params
    params.require(:property).permit(
      [:operation_type, :price, :currency, :community_id, :address, :area, :number_of_rooms, :number_of_bathrooms,
       :description, { images: [] }]
    )
  end

  def set_own_property
    @property = current_user.properties.find(params[:id])
  end

  # A list of the param names that can be used for filtering the Properties list
  def filtering_params
    params[:filter]&.permit(:operation_type, :community, :number_of_rooms).to_h
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
  def types_collection
    [
      [I18n.t(Property::RENT_TYPE), Property::RENT_TYPE],
      [I18n.t(Property::SALE_TYPE), Property::SALE_TYPE]
    ]
  end

  def currencies_collection
    %w[USD CLP]
  end

  def communities_collection
    Community.pluck(:name, :id)
  end

  def convert_price_for(property)
    response = RestClient.get('https://mindicador.cl/api/dolar')
    parsed_response = JSON.parse(response)
    indicator_value = parsed_response['serie']&.first&.[]('valor').to_f

    converted_value = property.price_in_usd? ? (property.price * indicator_value) : (property.price / indicator_value)

    ActiveSupport::NumberHelper.number_to_currency(converted_value, unit: property.price_in_usd? ? 'CLP' : 'USD')
  end
end

app/views/layouts/_flash_errors_explanation.html.erb
<div id="flash-errors-explanation" class="container">
  <div class="alert alert-danger">
    <h2><%= t('flash_message_errors', count: record.errors.count) %></h2>
    <ul>
      <% record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_flash_message.html.erb
<div id="flash-messages" class="container">
  <% flash.each do |type, message| %>

    <div class="alert alert-<%= type == 'notice' ? 'primary' : 'danger' %> alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DATAPROP</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body style="background: #f5f5f5">
<header class="bg-white border-bottom">
  <div class="container d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 ">
    <a class="navbar-brand d-flex align-items-center" href="<%= root_path %>">
      <img src="https://landing.dataprop.cl/wp-content/uploads/2023/04/Logo-dataprop2.png" class="d-inline-block align-text-top">
    </a>

    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
      <% if user_signed_in? %>
        <li class="nav-item text-black-50">
          <%= link_to t('own_properties').upcase, own_properties_properties_path, class: "nav-link text-black-50 #{ 'text-body-emphasis' if params[:action] == 'own_properties' }" %>
        </li>
      <% end %>
    </ul>

    <div class="col-md-3 text-end">
      <% unless %w[devise/sessions devise/registrations].include?(params[:controller]) %>
        <div class="d-flex justify-content-end">
          <% if user_signed_in? %>
            <div class="px-3"><%= t('logged_in_as_html', email: current_user.email) %> </div>
            <%= link_to t('sign_out'), destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-outline-secondary me-2' %>
          <% else %>
            <%= link_to t('sign_in'), new_user_session_path, class: 'btn btn-outline-primary me-2' %>
            <%= link_to t('sign_up'), new_user_registration_path, class: 'btn btn-primary' %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</header>

<div class="content min-vh-100 mt-2">
  <%= render partial: 'layouts/flash_message' %>

  <%= yield %>
</div>
</body>
</html>

app/views/own_properties/_form.html.erb
<% if @own_property.errors.any? %>
  <%= render 'layouts/flash_errors_explanation', record: @own_property %>
<% end %>

<div class="row mb-3">
  <div class="col-md-6 col-sm-12">
    <%= form.label :operation_type, class: 'form-label' %>
    <%= form.select :operation_type, types_collection, { selected: @own_property.operation_type, include_blank: true }, class: 'form-select' %>
  </div>

  <div class="col-md-6 col-sm-124">
    <%= form.label :community_id, class: 'form-label' %>
    <%= form.select :community_id, communities_collection, { selected: @own_property.community_id, include_blank: true }, class: 'form-select' %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-md-6 col-sm-12">
    <%= form.label :price, class: 'form-label' %>
    <%= form.number_field :price, class: 'form-control' %>
  </div>

  <div class="col-md-6 col-sm-12">
    <%= form.label :currency, class: 'form-label' %>
    <%= form.select :currency, currencies_collection, { selected: @own_property.currency, include_blank: true }, class: 'form-select' %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-12">
    <%= form.label :address, class: 'form-label' %>
    <%= form.text_field :address, class: 'form-control' %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-md-4 col-sm-12">
    <%= form.label :area, class: 'form-label' %>
    <%= form.number_field :area, class: 'form-control' %>
  </div>

  <div class="col-md-4 col-sm-12">
    <%= form.label :number_of_rooms, class: 'form-label' %>
    <%= form.number_field :number_of_rooms, class: 'form-control' %>
  </div>

  <div class="col-md-4 col-sm-12">
    <%= form.label :number_of_bathrooms, class: 'form-label' %>
    <%= form.number_field :number_of_bathrooms, class: 'form-control' %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-12">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-12">
    <% @own_property.images.each do |image| %>
      <%= image_tag image.variant(:thumb) %>

      <%= form.hidden_field :images, multiple: true, value: image.signed_id %>
    <% end %>
    <br>
    <%= form.label :images, class: 'form-label' %>
    <%= form.file_field :images, direct_upload: true, multiple: true, class: 'form-control', accept: 'image/png, image/jpg, image/jpeg' %>
  </div>
</div>

<div class="row">
  <div class="col-4">
    <%= form.submit t('save'), class: 'btn btn-primary' %>
  </div>
</div>

app/views/own_properties/edit.html.erb
<main class="container">
  <h1><%= t('edit_property') %></h1>
  <%= form_with model: @own_property, url: own_property_path, method: :put, data: { turbo: false } do |form| %>
    <%= render 'form', form: form %>
  <% end %>
</main>

app/views/own_properties/index.html.erb
<main class="container">
  <div class="row">
    <div class="col">

      <h1 class="display-4"><%= t('own_properties') %></h1>

      <div class="d-flex justify-content-end">
        <%= link_to new_own_property_path, class: 'btn btn-primary' do %>
          <i class="bi bi-plus-circle-fill"> <%= t('new_property') %></i>
        <% end %>
      </div>

      <% if @own_properties.present? %>
        <table class="table">
          <thead>
          <tr>
            <th scope="col"><%= t('activerecord.attributes.property.type') %></th>
            <th scope="col"><%= t('activerecord.attributes.property.price') %></th>
            <th scope="col"><%= t('activerecord.attributes.property.community_id') %></th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
          </thead>
          <tbody>
          <% @own_properties.each do |property| %>
            <tr>
              <th scope="row"><%= t(property.operation_type) %></th>
              <td><%= number_to_currency(property.price, unit: property.currency) %></td>
              <td><%= property.community_name %></td>
              <td>
                <%= link_to edit_own_property_path(property) do %>
                  <i class="bi bi-pencil-square"></i>
                <% end %>
              </td>
              <td>
                <%= link_to own_property_path(property), data: { turbo_method: :delete, turbo_confirm: t('are_you_sure') } do %>
                  <i class="bi bi-trash"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>

        <%= paginate @own_properties, remote: true %>

      <% else %>
        <p><%= t('not_own_properties') %></p>
      <% end %>
    </div>
  </div>
</main>

app/views/own_properties/new.html.erb
<main class="container">
  <h1><%= t('new_property') %></h1>
  <%= form_with model: @own_property, url: own_properties_path, method: :post, data: {turbo: false} do |form| %>
    <%= render 'form', form: form %>
  <% end %>
</main>

app/views/properties/_filters.html.erb
<%= form_with(scope: :filter, url: properties_path, method: :get, data: { controller: 'properties', properties_target: 'form', turbo_frame: 'properties' }) do |form| %>
  <div class="row mb-3">
    <div class="col-md-3 col-sm-12">
      <%= form.label t('activerecord.attributes.property.operation_type'), class: 'form-label' %>
      <%= form.select :operation_type, types_collection, { selected: params.dig('filter', 'operation_type'), include_blank: true }, class: 'form-select' %>
    </div>

    <div class="col-md-3 col-sm-12">
      <%= form.label t('activerecord.attributes.property.community'), class: 'form-label' %>
      <%= form.select :community, communities_collection, { selected: params.dig('filter', 'community_id'), include_blank: true }, class: 'form-select' %>
    </div>

    <div class="col-md-3 col-sm-12">
      <%= form.label t('activerecord.attributes.property.number_of_rooms'), class: 'form-label' %>
      <%= form.text_field :number_of_rooms, value: params.dig('filter', 'number_of_rooms'), class: 'form-control' %>
    </div>

    <div class="col-md-3 col-sm-12">
      <%= form.submit t('search'), class: 'btn btn-primary d-flex', style: 'margin-top: 2rem;' %>
    </div>
  </div>
<% end %>

app/views/properties/_form.html.erb
<% if @property.errors.any? %>
  <%= render 'layouts/flash_errors_explanation', record: @property %>
<% end %>

<div class="row mb-3">
  <div class="col-md-6 col-sm-12">
    <%= form.label :operation_type, class: 'form-label' %>
    <%= form.select :operation_type, types_collection, { selected: @property.operation_type, include_blank: true }, class: 'form-select' %>
  </div>

  <div class="col-md-6 col-sm-12">
    <%= form.label :community_id, class: 'form-label' %>
    <%= form.select :community_id, communities_collection, { selected: @property.community_id, include_blank: true }, class: 'form-select' %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-md-6 col-sm-12">
    <%= form.label :price, class: 'form-label' %>
    <%= form.number_field :price, class: 'form-control' %>
  </div>

  <div class="col-md-6 col-sm-12">
    <%= form.label :currency, class: 'form-label' %>
    <%= form.select :currency, currencies_collection, { selected: @property.currency, include_blank: true }, class: 'form-select' %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-12">
    <%= form.label :address, class: 'form-label' %>
    <%= form.text_field :address, class: 'form-control' %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-md-4 col-sm-12">
    <%= form.label :area, class: 'form-label' %>
    <%= form.number_field :area, class: 'form-control' %>
  </div>

  <div class="col-md-4 col-sm-12">
    <%= form.label :number_of_rooms, class: 'form-label' %>
    <%= form.number_field :number_of_rooms, class: 'form-control' %>
  </div>

  <div class="col-md-4 col-sm-12">
    <%= form.label :number_of_bathrooms, class: 'form-label' %>
    <%= form.number_field :number_of_bathrooms, class: 'form-control' %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-12">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-12">
    <% @property.images.each do |image| %>
      <%= image_tag image.variant(:thumb) %>

      <%= form.hidden_field :images, multiple: true, value: image.signed_id %>
    <% end %>
    <br>
    <%= form.label :images, class: 'form-label' %>
    <%= form.file_field :images, direct_upload: true, multiple: true, class: 'form-control', accept: 'image/png, image/jpg, image/jpeg' %>
  </div>
</div>

<div class="row">
  <div class="col-4">
    <%= form.submit t('save'), class: 'btn btn-primary' %>
  </div>
</div>

app/views/properties/edit.html.erb
<main class="container">
  <h1><%= t('edit_property') %></h1>
  <%= form_with model: @property, url: property_path, method: :put, data: { turbo: false } do |form| %>
    <%= render 'form', form: form %>
  <% end %>
</main>

app/views/properties/index.html.erb
<main class="container">
  <div class="row text-center justify-content-center">
    <div class="col">
      <h1 class="display-4"><%= t('home') %></h1>
    </div>

    <%= render 'filters' %>

    <%= turbo_frame_tag 'properties' do %>
      <main>
        <div class="container-fluid bg-trasparent my-4 p-3" style="position: relative;">
          <div class="row row-cols-1 row-cols-xs-2 row-cols-sm-2 row-cols-lg-4 g-3">
            <% @properties.each do |property| %>
              <div class="col" style="min-height: 420px">
                <div class="card h-100 shadow-sm border-0">
                  <%= image_tag property.images.first, class: 'card-img-top' %>
                  <div class="top-0 end-0 position-absolute rounded-1 text-white p-1 <%= property.rent? ? 'bg-secondary' : 'bg-primary' %>">
                    <%= t(property.operation_type) %>
                  </div>
                  <div class="card-body">
                    <div class="mb-3">
                      <span class="float-start badge rounded-pill bg-success">
                        <%= number_to_currency(property.price, unit: property.currency) %>
                      </span>
                    </div>
                    <br>
                    <div class="card-title d-flex flex-wrap">
                      <p><i class="bi bi-square-fill"></i> <%= t('activerecord.attributes.property.area') %>: <%= property.area %></p>
                      <p><i class="bi bi-person-workspace"></i> <%= t('activerecord.attributes.property.number_of_rooms') %>: <%= property.number_of_rooms %></p>
                      <p><i class="bi bi-cloud-sleet"></i> <%= t('activerecord.attributes.property.number_of_bathrooms') %>: <%= property.number_of_bathrooms %></p>
                    </div>

                    <div class="text-center my-4">
                      <%= link_to t('show_details'), property_path(property), target: '_blank', data: { turbo: false }, class: 'btn btn-warning' %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>

          </div>
        </div>

        <%= paginate @properties, remote: true %>
      </main>
    <% end %>
  </div>
</main>

app/views/properties/new.html.erb
<main class="container">
  <h1><%= t('new_property') %></h1>
  <%= form_with model: @property, url: properties_path, method: :post, data: {turbo: false} do |form| %>
    <%= render 'form', form: form %>
  <% end %>
</main>

app/views/properties/own_properties.html.erb
<main class="container">
  <div class="row">
    <div class="col">
      <div class="col d-flex justify-content-between align-items-center">
        <h1 class="display-4"><%= t('own_properties') %></h1>

        <div class="">
          <%= link_to new_property_path, class: 'btn btn-primary' do %>
            <i class="bi bi-plus-circle-fill"> <%= t('new_property') %></i>
          <% end %>
        </div>
      </div>

      <% if @properties.present? %>
        <table class="table">
          <thead>
          <tr>
            <th scope="col"><%= t('activerecord.attributes.property.type') %></th>
            <th scope="col"><%= t('activerecord.attributes.property.price') %></th>
            <th scope="col"><%= t('activerecord.attributes.property.community_id') %></th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
          </thead>
          <tbody>
          <% @properties.each do |property| %>
            <tr>
              <th scope="row"><%= t(property.operation_type) %></th>
              <td><%= number_to_currency(property.price, unit: property.currency) %></td>
              <td><%= property.community_name %></td>
              <td>
                <%= link_to edit_property_path(property) do %>
                  <i class="bi bi-pencil-square"></i>
                <% end %>
              </td>
              <td>
                <%= link_to property_path(property), data: { turbo_method: :delete, turbo_confirm: t('are_you_sure') } do %>
                  <i class="bi bi-trash"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>

        <%= paginate @properties, remote: true %>

      <% else %>
        <div class="alert alert-danger" role="alert">
          <%= t('not_own_properties') %>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/properties/show.html.erb
<main class="container justify-content-center">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to t('home'), root_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= truncate(@property.description.present? ? @property.description : @property.id.to_s, length: 25) %>
      </li>
    </ol>
  </nav>

  <div class="row">
    <div id="carouselPropertyImages" class="carousel slide col-md-8" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <% 0.upto(@property.images.count - 1) do |index| %>
          <button type="button" data-bs-target="#carouselPropertyImages" data-bs-slide-to="<%= index %>" class="<%= 'active' if index.zero? %>" aria-current="true" aria-label="Slide <%= index %>"></button>
        <% end %>
      </div>

      <div class="carousel-inner rounded-2">
        <% @property.images.each_with_index do |image, index| %>
          <div class="carousel-item <%= 'active' if index.zero? %>">
            <%= image_tag image, class: 'card-img-top' %>
            <div class="carousel-caption d-none d-md-block">
              <h5><%= number_to_currency(@property.price, unit: @property.currency) %></h5>
              <p><%= @property.description %></p>
            </div>
          </div>
        <% end %>
      </div>

      <button class="carousel-control-prev" type="button" data-bs-target="#carouselPropertyImages" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden"><%= t('previous') %></span>
      </button>
      <button class="carousel-control-next fw-bolder" type="button" data-bs-target="#carouselPropertyImages" data-bs-slide="next">
        <span class="carousel-control-next-icon fw-bolder" aria-hidden="true"></span>
        <span class="visually-hidden"><%= t('next') %></span>
      </button>
    </div>
    <div class="col-md-4">
      <div class="card border-0">
        <div class="card-body">
          <p class="card-title">
            <i class="bi bi-receipt"></i> <%= t('activerecord.attributes.property.operation_type') %>: <%= t(@property.operation_type) %>
          </p>
          <p class="card-title">
            <i class="bi bi-receipt"></i> <%= t('activerecord.attributes.property.price') %>: <%= number_to_currency(@property.price, unit: @property.currency) %> <small>(<%= convert_price_for(@property) %>)</small>
          </p>
          <p class="card-title">
            <i class="bi bi-geo-alt-fill"></i> <%= t('activerecord.attributes.property.address') %>: <%= @property.address %>
          </p>
          <p class="card-title">
            <i class="bi bi-square-fill"></i> <%= t('activerecord.attributes.property.area') %>: <%= @property.area %>
          </p>
          <p class="card-title">
            <i class="bi bi-person-workspace"></i> <%= t('activerecord.attributes.property.number_of_rooms') %>: <%= @property.number_of_rooms %>
          </p>
          <p class="card-title">
            <i class="bi bi-cloud-sleet"></i> <%= t('activerecord.attributes.property.number_of_bathrooms') %>: <%= @property.number_of_bathrooms %>
          </p>
          <p class="card-title">
            <i class="bi bi-cloud-sleet"></i> <%= t('activerecord.attributes.property.description') %>: <%= @property.description %>
          </p>
        </div>
      </div>
    </div>
  </div>
</main>